### PR TITLE
Init travis

### PR DESCRIPTION
**Pull request by lsetiawan**
## Overview
This PR initialize Travis CI and use Jeff's Envirodiy specimen test database to run testing. 

## Notes
- `odm2api` is installed manually by Travis using the github repository development branch.
- `djangorestframework-csv`, `djangorestframework-xml`, and `djangorestframework-yaml` are currently installed using pip since there is no conda packages for these yet.

### CODE REVIEW

**Comment by lsetiawan** [comment]
@ocefpaf My first travis-ci! :smile: Pretty proud of myself! Thanks for the template haha Nothing to do for you here, just though I should share.

**Comment by emiliom** [comment]
@lsetiawan Nice to see this CI progress. However, I won't be able to review or participate in any REST API work from now until after Christmas .... So, merge this and other PR's at your discretion.

The only comment I would make is about the use of the AWS-hosted test API and database for CI testing. The benefit is obvious. But I'm concerned about the potential impact on cloud use costs (with BiGCZ funding no longer available) given that every PR will now result in a use of the AWS test API. But, obviously I have no idea whether that cost would be "trivial". So, I don't have constructive comments, except, be on the lookout for the cost impact of this CI tests, and if they are significant, mention it to @aufdenkampe (in my absence) to look at options.

**Comment by lsetiawan** [comment]
@emiliom This CI is using local deployment of Jeff's database :smile: Thanks to @ocefpaf for figuring this out for WOFpy, so I'm just using his template here. So no cloud that we own is involved here.

**Comment by horsburgh** [comment]
@lsetiawan and @emiliom - we do have capabilities here to stand up sandbox machines in our "private cloud." What are the specs of the machine you are using in AWS to host the testing environment? We might be able to create a machine here and give you guys access to it. Firewalls would have to be poked.

**Comment by emiliom** [comment]
Thanks for the offer, @horsburgh! That could be very helpful if we can make it work. Please discuss with @lsetiawan to decide if that's a workable option for our test deployments. @lsetiawan, please follow up on Jeff's questions:

> What are the specs of the machine you are using in AWS to host the testing environment?

You might want to jump to email to discuss this, since the topic is not specific to one software.

**Comment by lsetiawan** [comment]
@horsburgh I am using AWS t2.small. I am currently using docker to do all testings.

**Pull request merged**
