### PR TITLE
Fix SamplingFeature Datasets to match python api data structure

### PR DESCRIPTION
**Pull request by lsetiawan**
## Overview

This PR updates `/samplingfeaturedatasets` endpoint to match the data structure within odm2pythonapi.

Relates to Issue #19 

## Demo

http://54.186.36.247:8001/v1/samplingfeaturedatasets?samplingFeatureID=1064

### CODE REVIEW

**Comment by lsetiawan** [comment]
@horsburgh Let me know if that's the structure you're looking for on this one. Thanks!

**Comment by emiliom** [comment]
Thanks @lsetiawan. I'll be offline for the next 1.5 hours, plus I'd have to first learn what the `samplingfeaturedatasets` data structure looks like. So, either @horsburgh gets to review this first, or I'll get to it by the end of the day ... or later.

**Comment by emiliom** [comment]
Looks good. But as we just discussed, looking at this response and the corresponding endpoint description in the REST API Google doc brings up broader questions about what specifically should (and shouldn't?) be included in the response. I'll comment on this via issue #19; please don't close that issue at this time, even though this PR **does** implement the endpoint!

**Comment by horsburgh** [comment]
@lsetiawan - I think the approval of the response content and structure should go in a separate issue. I think all of the endpoints need to be reviewed now that we have initial implementations. And, as your discussions point out, this issue is tied to the Python API because the job of the REST API is to simply serialize the objects that are returned from the Python API.

**Comment by emiliom** [comment]
Continuing general discussions at #58

**Pull request merged**
