### PR TITLE
App rename and folder restructuring

### PR DESCRIPTION
**Pull request by lsetiawan**
## Overview

This PR renames `api` to a cleared name as `odm2_rest_api` I am doing this so that we can have a reusable app that will probably be called `django-odm2-rest-api`, which then applications like `ODM2-Admin` or other django app can use this within the application rather than separately. The details are still in flux.

### CODE REVIEW

**Comment by emiliom** [comment]
Let's talk about it a bit, before merging.

**Comment by lsetiawan** [comment]
## Note

Failures are due to incorrect testing mechanism. `python examples/manage.py test odm2rest;` does not work for installed pip packages. I get

```
ImportError: 'tests' module incorrectly imported from '/home/travis/miniconda/envs/TEST/lib/python2.7/site-packages/odm2rest'. Expected '/home/travis/build/ODM2/ODM2RESTfulWebServices/odm2rest'. Is this module globally installed?
```

**Comment by lsetiawan** [comment]
@emiliom I've changed the name to `odm2rest` let me know if you like that. If so, I'll merge this for now as I work on figuring out the fix to travis and the correct testing way.

**Comment by emiliom** [comment]
> @emiliom I've changed the name to `odm2rest`

That's exactly what I was going to suggest just now! I like hos it's brief and consistent/parallel with `odm2api`. 

There's no way I can truly review this PR. So, I trust you :wink:. TravisCI failed, but I can't remember if there are tests that are working. So, you have my blessing to merge the PR yourself :+1:

**Pull request merged**
