### PR TITLE
Add Datasets Endpoints

### PR DESCRIPTION
**Pull request by lsetiawan**
## Overview

This PR adds Data Sets API Endpoints `/datasets`.  Also I have separated each step to different commits so that @Elijahwalkerwest can easily follow the steps I take in adding new endpoints.

### CODE REVIEW

**Comment by emiliom** [comment]
Thanks! Do you want me to review and merge, or are you planning to ask @Elijahwalkerwest to do that?

**Comment by lsetiawan** [comment]
@emiliom You don't need to review this change. I would like @Elijahwalkerwest to start review code and let me know if he has any questions. I'll merge when he has no questions. Thanks! 😄

**Comment by Elijahwalkerwest** [comment]
Thanks, reviewing now.

**Comment by lsetiawan** [comment]
I am merging this @Elijahwalkerwest, you can always refer back if needed, but I need to proceed with development. Thanks.

**Comment by emiliom** [comment]
:+1:

**Pull request merged**
